import { demoMatch } from "./demo-match";
import type { ScoutSession } from "./scout";
import type { CodedAction } from "./volley-codes";

/** Deterministic demo scout session with video timestamps matching sample video peaks. */
export function createDemoScoutSession(): ScoutSession {
  const now = new Date().toISOString();
  const actions: CodedAction[] = [
    {
      id: "da1",
      setIndex: 0,
      rallyIndex: 0,
      team: "home",
      skill: "S",
      effect: "#",
      playerNumber: 7,
      playerName: "김하늘",
      rotation: 1,
      videoTimeSec: 2.8,
      pointEnding: true,
    },
    {
      id: "da2",
      setIndex: 0,
      rallyIndex: 1,
      team: "home",
      skill: "A",
      effect: "#",
      playerNumber: 7,
      playerName: "김하늘",
      endZone: 4,
      rotation: 1,
      combination: "X5",
      videoTimeSec: 3.6,
      pointEnding: true,
    },
    {
      id: "da3",
      setIndex: 0,
      rallyIndex: 2,
      team: "away",
      skill: "A",
      effect: "#",
      playerNumber: 8,
      playerName: "류태양",
      endZone: 2,
      rotation: 1,
      combination: "X5",
      videoTimeSec: 8.5,
      pointEnding: true,
    },
    {
      id: "da4",
      setIndex: 0,
      rallyIndex: 3,
      team: "home",
      skill: "B",
      effect: "#",
      playerNumber: 4,
      playerName: "이준호",
      endZone: 3,
      rotation: 1,
      videoTimeSec: 15.2,
      pointEnding: true,
    },
    {
      id: "da5",
      setIndex: 0,
      rallyIndex: 4,
      team: "home",
      skill: "A",
      effect: "#",
      playerNumber: 10,
      playerName: "박세린",
      endZone: 2,
      rotation: 2,
      combination: "Pipe",
      videoTimeSec: 16.5,
      pointEnding: true,
    },
    {
      id: "da6",
      setIndex: 0,
      rallyIndex: 5,
      team: "home",
      skill: "A",
      effect: "+",
      playerNumber: 7,
      playerName: "김하늘",
      endZone: 4,
      rotation: 2,
      combination: "X5",
      videoTimeSec: 12,
    },
    {
      id: "da7",
      setIndex: 1,
      rallyIndex: 0,
      team: "home",
      skill: "S",
      effect: "#",
      playerNumber: 7,
      playerName: "김하늘",
      rotation: 2,
      videoTimeSec: 9.5,
      pointEnding: true,
    },
  ];

  return {
    id: "demo-scout-session",
    matchId: demoMatch.id,
    title: demoMatch.title,
    createdAt: now,
    updatedAt: now,
    homeName: demoMatch.home.name,
    awayName: demoMatch.away.name,
    homeRotation: 2,
    awayRotation: 1,
    actions,
    points: [
      {
        id: "d1",
        setIndex: 0,
        pointIndex: 0,
        serving: "home",
        winner: "home",
        termination: "ace",
        playerId: "fav-1",
        playerNumber: 7,
        playerName: "김하늘",
        videoTimeSec: 2.8,
        homeRotation: 1,
        awayRotation: 1,
        endSkill: "S",
        endEffect: "#",
      },
      {
        id: "d2",
        setIndex: 0,
        pointIndex: 1,
        serving: "home",
        winner: "home",
        termination: "kill",
        playerId: "fav-1",
        playerNumber: 7,
        playerName: "김하늘",
        videoTimeSec: 3.6,
        homeRotation: 1,
        awayRotation: 1,
        endSkill: "A",
        endEffect: "#",
        endZone: 4,
        combination: "X5",
      },
      {
        id: "d3",
        setIndex: 0,
        pointIndex: 2,
        serving: "away",
        winner: "away",
        termination: "kill",
        playerId: "seo-1",
        playerNumber: 8,
        playerName: "류태양",
        videoTimeSec: 8.5,
        homeRotation: 1,
        awayRotation: 1,
        endSkill: "A",
        endEffect: "#",
        endZone: 2,
        combination: "X5",
      },
      {
        id: "d4",
        setIndex: 0,
        pointIndex: 3,
        serving: "away",
        winner: "home",
        termination: "block",
        playerId: "fav-3",
        playerNumber: 4,
        playerName: "이준호",
        videoTimeSec: 15.2,
        homeRotation: 1,
        awayRotation: 1,
        endSkill: "B",
        endEffect: "#",
        endZone: 3,
      },
      {
        id: "d5",
        setIndex: 0,
        pointIndex: 4,
        serving: "home",
        winner: "home",
        termination: "kill",
        playerId: "fav-2",
        playerNumber: 10,
        playerName: "박세린",
        videoTimeSec: 16.5,
        homeRotation: 2,
        awayRotation: 1,
        endSkill: "A",
        endEffect: "#",
        endZone: 2,
        combination: "Pipe",
      },
      {
        id: "d6",
        setIndex: 1,
        pointIndex: 0,
        serving: "away",
        winner: "home",
        termination: "ace",
        playerId: "fav-1",
        playerNumber: 7,
        playerName: "김하늘",
        videoTimeSec: 9.5,
        homeRotation: 2,
        awayRotation: 1,
        endSkill: "S",
        endEffect: "#",
      },
    ],
  };
}
