import { demoMatch } from "./demo-match";
import type { ScoutSession } from "./scout";

/** Deterministic demo scout session with video timestamps matching sample video peaks. */
export function createDemoScoutSession(): ScoutSession {
  const now = new Date().toISOString();
  return {
    id: "demo-scout-session",
    matchId: demoMatch.id,
    title: demoMatch.title,
    createdAt: now,
    updatedAt: now,
    homeName: demoMatch.home.name,
    awayName: demoMatch.away.name,
    points: [
      {
        id: "d1",
        setIndex: 0,
        pointIndex: 0,
        serving: "home",
        winner: "home",
        termination: "ace",
        playerId: "fav-1",
        playerNumber: 7,
        playerName: "김하늘",
        videoTimeSec: 2.8,
      },
      {
        id: "d2",
        setIndex: 0,
        pointIndex: 1,
        serving: "home",
        winner: "home",
        termination: "kill",
        playerId: "fav-1",
        playerNumber: 7,
        playerName: "김하늘",
        videoTimeSec: 3.6,
      },
      {
        id: "d3",
        setIndex: 0,
        pointIndex: 2,
        serving: "away",
        winner: "away",
        termination: "kill",
        playerId: "seo-1",
        playerNumber: 8,
        playerName: "류태양",
        videoTimeSec: 8.5,
      },
      {
        id: "d4",
        setIndex: 0,
        pointIndex: 3,
        serving: "away",
        winner: "home",
        termination: "block",
        playerId: "fav-3",
        playerNumber: 4,
        playerName: "이준호",
        videoTimeSec: 15.2,
      },
      {
        id: "d5",
        setIndex: 0,
        pointIndex: 4,
        serving: "home",
        winner: "home",
        termination: "kill",
        playerId: "fav-2",
        playerNumber: 10,
        playerName: "박세린",
        videoTimeSec: 16.5,
      },
      {
        id: "d6",
        setIndex: 1,
        pointIndex: 0,
        serving: "away",
        winner: "home",
        termination: "ace",
        playerId: "fav-1",
        playerNumber: 7,
        playerName: "김하늘",
        videoTimeSec: 9.5,
      },
    ],
  };
}
