import type { MatchInput, PlayerStats } from "./types";

function player(
  partial: Omit<PlayerStats, "sets" | "setErrors"> & {
    sets?: number;
    setErrors?: number;
  },
): PlayerStats {
  return {
    sets: 0,
    setErrors: 0,
    ...partial,
  };
}

export const demoMatch: MatchInput = {
  id: "fav-vs-seoul-2026-03-21",
  title: "FAV vs 서울 윙스 — 정규리그 12라운드",
  date: "2026-03-21",
  venue: "FAV 아레나",
  home: {
    name: "FAV",
    shortName: "FAV",
    isFav: true,
    setScores: [25, 22, 25, 27],
    players: [
      player({
        id: "fav-1",
        name: "김하늘",
        number: 7,
        position: "OH",
        attacks: 28,
        kills: 14,
        attackErrors: 4,
        blocks: 2,
        digs: 11,
        aces: 3,
        serveErrors: 2,
        receptions: 16,
        receptionErrors: 1,
      }),
      player({
        id: "fav-2",
        name: "박세린",
        number: 10,
        position: "OPP",
        attacks: 32,
        kills: 16,
        attackErrors: 5,
        blocks: 1,
        digs: 6,
        aces: 2,
        serveErrors: 3,
        receptions: 2,
        receptionErrors: 0,
      }),
      player({
        id: "fav-3",
        name: "이준호",
        number: 4,
        position: "MB",
        attacks: 14,
        kills: 8,
        attackErrors: 1,
        blocks: 6,
        digs: 3,
        aces: 1,
        serveErrors: 1,
        receptions: 0,
        receptionErrors: 0,
      }),
      player({
        id: "fav-4",
        name: "최다은",
        number: 12,
        position: "MB",
        attacks: 11,
        kills: 5,
        attackErrors: 2,
        blocks: 4,
        digs: 2,
        aces: 0,
        serveErrors: 1,
        receptions: 0,
        receptionErrors: 0,
      }),
      player({
        id: "fav-5",
        name: "정우성",
        number: 3,
        position: "S",
        attacks: 4,
        kills: 2,
        attackErrors: 0,
        blocks: 1,
        digs: 8,
        aces: 1,
        serveErrors: 1,
        receptions: 0,
        receptionErrors: 0,
        sets: 68,
        setErrors: 3,
      }),
      player({
        id: "fav-6",
        name: "한지우",
        number: 1,
        position: "L",
        attacks: 0,
        kills: 0,
        attackErrors: 0,
        blocks: 0,
        digs: 18,
        aces: 0,
        serveErrors: 0,
        receptions: 22,
        receptionErrors: 2,
      }),
      player({
        id: "fav-7",
        name: "오민재",
        number: 9,
        position: "OH",
        attacks: 19,
        kills: 7,
        attackErrors: 5,
        blocks: 1,
        digs: 9,
        aces: 1,
        serveErrors: 2,
        receptions: 14,
        receptionErrors: 3,
      }),
    ],
  },
  away: {
    name: "서울 윙스",
    shortName: "서울",
    setScores: [20, 25, 19, 25],
    players: [
      player({
        id: "seo-1",
        name: "류태양",
        number: 8,
        position: "OH",
        attacks: 30,
        kills: 12,
        attackErrors: 6,
        blocks: 1,
        digs: 10,
        aces: 4,
        serveErrors: 4,
        receptions: 15,
        receptionErrors: 3,
      }),
      player({
        id: "seo-2",
        name: "신예린",
        number: 15,
        position: "OPP",
        attacks: 34,
        kills: 15,
        attackErrors: 7,
        blocks: 2,
        digs: 5,
        aces: 2,
        serveErrors: 3,
        receptions: 1,
        receptionErrors: 0,
      }),
      player({
        id: "seo-3",
        name: "강도윤",
        number: 5,
        position: "MB",
        attacks: 12,
        kills: 5,
        attackErrors: 2,
        blocks: 3,
        digs: 2,
        aces: 1,
        serveErrors: 2,
        receptions: 0,
        receptionErrors: 0,
      }),
      player({
        id: "seo-4",
        name: "문채원",
        number: 11,
        position: "MB",
        attacks: 9,
        kills: 3,
        attackErrors: 2,
        blocks: 2,
        digs: 1,
        aces: 0,
        serveErrors: 1,
        receptions: 0,
        receptionErrors: 0,
      }),
      player({
        id: "seo-5",
        name: "배서준",
        number: 2,
        position: "S",
        attacks: 3,
        kills: 1,
        attackErrors: 1,
        blocks: 0,
        digs: 7,
        aces: 1,
        serveErrors: 2,
        receptions: 0,
        receptionErrors: 0,
        sets: 62,
        setErrors: 5,
      }),
      player({
        id: "seo-6",
        name: "윤소라",
        number: 6,
        position: "L",
        attacks: 0,
        kills: 0,
        attackErrors: 0,
        blocks: 0,
        digs: 14,
        aces: 0,
        serveErrors: 0,
        receptions: 24,
        receptionErrors: 5,
      }),
      player({
        id: "seo-7",
        name: "조현",
        number: 14,
        position: "OH",
        attacks: 17,
        kills: 6,
        attackErrors: 4,
        blocks: 1,
        digs: 8,
        aces: 1,
        serveErrors: 2,
        receptions: 12,
        receptionErrors: 2,
      }),
    ],
  },
};
