import type { MatchAnalysis, MatchInput } from "./types";
import type { ScoutSession, SideOutStats } from "./scout";
import { analyzeSideOut, computeSetScores } from "./scout";
import { pct, scoreLabel } from "./analysis";

export function buildMarkdownReport(
  match: MatchInput,
  analysis: MatchAnalysis,
  scout?: ScoutSession | null,
): string {
  const lines: string[] = [];
  lines.push(`# ${match.title}`);
  lines.push("");
  lines.push(`- 날짜: ${match.date}`);
  lines.push(`- 장소: ${match.venue}`);
  lines.push(`- 세트: ${analysis.setScore}`);
  lines.push(
    `- 승자: ${
      analysis.winner === "home"
        ? match.home.name
        : analysis.winner === "away"
          ? match.away.name
          : "접전"
    }`,
  );
  lines.push("");
  lines.push(`## ${match.home.name} (${scoreLabel(analysis.home.overall)} ${analysis.home.overall.toFixed(0)})`);
  lines.push(`- 공격효율 ${pct(analysis.home.attackEfficiency)} / 킬률 ${pct(analysis.home.killRate)}`);
  lines.push(`- 블로킹 ${analysis.home.blockPoints} / 에이스 ${analysis.home.aceTotal}`);
  lines.push(`- 강점: ${analysis.home.strengths.join(" / ")}`);
  lines.push(`- 약점: ${analysis.home.weaknesses.join(" / ")}`);
  lines.push("");
  lines.push(`## ${match.away.name} (${scoreLabel(analysis.away.overall)} ${analysis.away.overall.toFixed(0)})`);
  lines.push(`- 공격효율 ${pct(analysis.away.attackEfficiency)} / 킬률 ${pct(analysis.away.killRate)}`);
  lines.push(`- 블로킹 ${analysis.away.blockPoints} / 에이스 ${analysis.away.aceTotal}`);
  lines.push("");
  lines.push("## 매치업 노트");
  for (const n of analysis.matchupNotes) lines.push(`- ${n}`);
  lines.push("");
  lines.push("## 코칭 플랜");
  analysis.coachingPlan.forEach((n, i) => lines.push(`${i + 1}. ${n}`));

  if (scout?.points?.length) {
    const side: SideOutStats = analyzeSideOut(scout.points);
    const sets = computeSetScores(scout.points);
    lines.push("");
    lines.push("## 포인트 스카우트");
    lines.push(`- 포인트 수: ${scout.points.length}`);
    lines.push(
      `- 사이드아웃: HOME ${pct(side.homeSideOutRate)} / AWAY ${pct(side.awaySideOutRate)}`,
    );
    lines.push(
      `- 최장 연속득점: HOME ${side.longestHomeRun} / AWAY ${side.longestAwayRun}`,
    );
    lines.push(
      `- 세트: ${sets.map((s) => `${s.home}-${s.away}`).join(", ")}`,
    );
  }

  lines.push("");
  lines.push("## 핵심 선수 (HOME)");
  for (const p of analysis.home.keyPlayers) {
    lines.push(
      `- #${p.number} ${p.name} (${p.position}) ${p.overall.toFixed(0)} · ${p.tags.join(", ")}`,
    );
  }
  lines.push("");
  lines.push("_Generated by FAV Scout_");
  return lines.join("\n");
}

export function downloadTextFile(filename: string, content: string, mime = "text/plain"): void {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function openPrintableReport(markdown: string, title: string): void {
  const html = `<!doctype html><html lang="ko"><head><meta charset="utf-8"/><title>${escapeHtml(
    title,
  )}</title>
  <style>
    body{font-family:Georgia,serif;max-width:800px;margin:2rem auto;padding:0 1rem;line-height:1.5;color:#111}
    h1,h2{font-family:Arial,sans-serif}
    pre{white-space:pre-wrap;font-family:ui-monospace,monospace;background:#f6f6f6;padding:1rem;border-radius:8px}
    @media print{body{margin:0}}
  </style></head><body>
  <pre>${escapeHtml(markdown)}</pre>
  <script>window.onload=()=>setTimeout(()=>window.print(),200)</script>
  </body></html>`;
  const w = window.open("", "_blank");
  if (!w) return;
  w.document.write(html);
  w.document.close();
}

function escapeHtml(s: string): string {
  return s
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}
